### ISSUE TITLE
REL: Final tasks

### ISSUE THREAD

**Issue by HaoZeke** [seldon-code/pyseldonlib#9]
- [x] Come up with a new name (`pyseldon` is "too close") to `pyseidon`.
- [x] Use dynamic versioning
- [x] Build wheels only on the main repository `seldon-code/pyseldon`

**Comment by HaoZeke** [comment]
@MSallermann @amritagos @imtambovtcev new name suggestions very welcome! SnakeSeldon seems to be free...

**Comment by HaoZeke** [comment]
After discussion Psiseldon is free and seems to be the way to go. @User-DK I'm renaming the repo

**Comment by User-DK** [comment]
I think pyseldonlib would be better and do we need to change the name of the repo? we can just have package name as `pyseldonlib`

**Comment by HaoZeke** [comment]
PySeldonLib it is! Excellent name choice. And yup the upstream repo (this one) along with the package name needs to be changed, but your fork can remain at the old name.
